### PR TITLE
support adding and editing tags and subscriptions

### PR DESCRIPTION
**Pull request by dave-atx**
Added an implementation of the `tag/list` API call. This allows NetNewsWire on macOS to connect to miniflux via the greader API and view feeds.

### CODE REVIEW

**Comment by dave-atx** [comment]
@gergan I added several more methods for adding and editing tags and subscriptions. I think most / all of the API may be covered now. I've been testing with NetNewsWire, and absent a couple of bugs in that app it's pretty functional.

**Comment by gergan** [comment]
@dave-atx great news - I'll try to look at it/ test it with Reeder/merge it tomorrow

**Comment by dave-atx** [comment]
Thanks, @gergan !

**Comment by gergan** [comment]
Sorry - I'll not have the time to look at this till the end of the month. So if @bastikempken could, he has write permissions - so he'll be able to merge it. The other possibility is to just merge it and after that correct whatever comes in the pull request, which still needs tests and probably some more love...

**Comment by bastikempken** [comment]
I will try to find some time @dave-atx thx in adavance

**Comment by dave-atx** [comment]
@bastikempken @gergan anything I can do to help get the overall reader API PR into shape to get merged?

**Comment by gergan** [comment]
Sorry @dave-atx I really didn't/don't have time to look at your pull request, but as this fork is mostly a work in progress, I'll be merging your pull request and if we need to make changes, will make them direct on the fork.

**Pull request merged**
